name = "RhesCraft"
author = "Rhestia"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b68e7509b8157dda23e851ac63327ce9e97e27e44eaaf2006e19693bd99c6b8"

[versions]
forge = "43.1.65"
minecraft = "1.19.2"
