name = "RhesCraft"
author = "Rhestia"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "984c8655f65a406609588873c22607fcde10f514ea12b2dc85b73f17b7b58ca2"

[versions]
forge = "43.1.55"
minecraft = "1.19.2"
