name = "RhesCraft"
author = "Rhestia"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c73ff42a37624685d25a0a4a8bb53754000ade4811a229b4a8f98970d34c16ab"

[versions]
forge = "43.1.55"
minecraft = "1.19.2"
