name = "RhesCraft"
author = "Rhestia"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83ccc5b23fc96b34c46649bbb138866f466181d82417afbb11e3f06df63be425"

[versions]
forge = "43.2.1"
minecraft = "1.19.2"
